# Augur AI Security Lockdown Script
# Fleet-Wide Security Hardening for tr3asure mAp
# Generated by Sir Green's OODA Loop

param(
    [string]$TargetShip = "SQUIDSTATION",
    [switch]$ApplyRules,
    [switch]$VerifyOnly
)

# Fleet IP Addresses (Tailscale)
$FleetIPs = @{
    "SQUIDSTATION" = "192.168.0.39"
    "PINKCADY"     = "192.168.0.3"  
    "STEALTHATTACK"= "100.83.247.14"
}

# Security Policy Definition
$SecurityRules = @{
    "DockerAPI"     = @{Port=2375; Action="Block"; Profile="Public"}
    "RedisExternal" = @{Port=6379; Action="Block"; Profile="Public"}
    "DockerTLS"     = @{Port=2376; Allow=$FleetIPs["SQUIDSTATION"]; Profile="Any"}
    "Grafana"       = @{Port=3000; Allow=$FleetIPs["SQUIDSTATION"]; Profile="Any"}
    "BackendAPI"    = @{Port=5000; Allow=@($FleetIPs["SQUIDSTATION"],$FleetIPs["PINKCADY"]); Profile="Any"}
    "Dashboard"     = @{Port=8080; Allow=@($FleetIPs["SQUIDSTATION"],$FleetIPs["PINKCADY"]); Profile="Any"}
    "Prometheus"    = @{Port=9090; Allow=$FleetIPs["SQUIDSTATION"]; Profile="Any"}
}

function Write-AuditLog {
    param([string]$Message)
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logEntry = "[$timestamp] $Message"
    Write-Host $logEntry
    Add-Content -Path "$PSScriptRoot\..\..\audit_logs\augur_security_audit.log" -Value $logEntry
}

# Main execution
Write-AuditLog "Starting security lockdown for $TargetShip"

foreach ($rule in $SecurityRules.GetEnumerator()) {
    $ruleName = "tr3asure-$($rule.Key)"
    $port = $rule.Value.Port
    $action = if ($rule.Value.Action -eq "Block") { "Block" } else { "Allow" }
    
    Write-AuditLog "Processing $ruleName on port $port ($action)"
    
    if ($ApplyRules) {
        try {
            if ($rule.Value.Action -eq "Block") {
                netsh advfirewall firewall add rule name="$ruleName" dir=in action=block protocol=TCP localport=$port remoteip="localsubnet" profile=$($rule.Value.Profile)
            } else {
                $allowList = $rule.Value.Allow -join ","
                netsh advfirewall firewall add rule name="$ruleName" dir=in action=allow protocol=TCP localport=$port remoteip="$allowList" profile=$($rule.Value.Profile)
            }
            Write-AuditLog "✓ $ruleName applied successfully"
        } catch {
            Write-AuditLog "✗ Failed to apply $ruleName : $_"
        }
    }
}

# Verification phase
if ($VerifyOnly -or $ApplyRules) {
    Write-AuditLog "Running verification..."
    netstat -an | findstr "2375 2376 5000 6379 8080 3000 9090" | Out-File -FilePath "$PSScriptRoot\..\..\evidence\post_lockdown_ports_$TargetShip.txt"
    Write-AuditLog "Verification complete - evidence saved"
}

Write-AuditLog "Security lockdown sequence completed"
