# Fleet Firewall Hardening Script for SQUIDSTATION
# Generated by Sir Green - Fleet Security Protocol
# SAFE MODE: Conservative hardening - only blocks external access

# === SAFEGUARD BLOCKS ===
# These allow rules must remain to prevent lockout
$fleet_ips = @(192.168.0.39,192.168.0.3,100.83.247.14)
$local_subnet = "192.168.0.0/24"
$tailscale_subnet = "100.64.0.0/10"

Write-Host "=== SQUIDSTATION Hardening Initiated ===" -ForegroundColor Cyan

# === ALLOW RULES (INTERNAL ONLY) ===
# Fleet members + local network + Tailscale
Write-Host "Configuring ALLOW rules..." -ForegroundColor Yellow

# SSH (for Captain/Admin access)
netsh advfirewall firewall add rule name="SSH-LocalAndFleet" dir=in action=allow protocol=TCP localport=22 remoteip="192.168.0.39,192.168.0.3,100.83.247.14,192.168.0.0/24,100.64.0.0/10" profile=any enable=yes
# RDP for Captain
netsh advfirewall firewall add rule name="RDP-CaptainOnly" dir=in action=allow protocol=TCP localport=3389 remoteip="192.168.0.39" profile=any enable=yes
# Docker TLS
netsh advfirewall firewall add rule name="Docker-TLS-FleetOnly" dir=in action=allow protocol=TCP localport=2376 remoteip="192.168.0.39,192.168.0.3,100.83.247.14,192.168.0.0/24" profile=any enable=yes
# Dashboard
netsh advfirewall firewall add rule name="Dashboard-FleetOnly" dir=in action=allow protocol=TCP localport=8080 remoteip="192.168.0.39,192.168.0.3,100.83.247.14,192.168.0.0/24,100.64.0.0/10" profile=any enable=yes
# Prometheus
netsh advfirewall firewall add rule name="Prometheus-FleetOnly" dir=in action=allow protocol=TCP localport=9090 remoteip="192.168.0.39,192.168.0.3,100.83.247.14,192.168.0.0/24,100.64.0.0/10" profile=any enable=yes
# Alertmanager
netsh advfirewall firewall add rule name="Alertmanager-FleetOnly" dir=in action=allow protocol=TCP localport=9093 remoteip="192.168.0.39,192.168.0.3,100.83.247.14,192.168.0.0/24,100.64.0.0/10" profile=any enable=yes
# Application ports
netsh advfirewall firewall add rule name="squidstation-Port3000-FleetOnly" dir=in action=allow protocol=TCP localport=3000 remoteip="192.168.0.39,192.168.0.0/24,100.64.0.0/10" profile=any enable=yes
netsh advfirewall firewall add rule name="squidstation-Port8080-FleetOnly" dir=in action=allow protocol=TCP localport=8080 remoteip="192.168.0.39,192.168.0.0/24,100.64.0.0/10" profile=any enable=yes
netsh advfirewall firewall add rule name="squidstation-Port9090-FleetOnly" dir=in action=allow protocol=TCP localport=9090 remoteip="192.168.0.39,192.168.0.0/24,100.64.0.0/10" profile=any enable=yes
netsh advfirewall firewall add rule name="squidstation-Port9093-FleetOnly" dir=in action=allow protocol=TCP localport=9093 remoteip="192.168.0.39,192.168.0.0/24,100.64.0.0/10" profile=any enable=yes

# === BLOCK RULES (EXTERNAL ONLY) ===
Write-Host "Configuring BLOCK rules..." -ForegroundColor Yellow

# Block Docker API (insecure) from all external sources
netsh advfirewall firewall add rule name="Block-DockerAPI-External" dir=in action=block protocol=TCP localport=2375 remoteip="localsubnet" profile=public enable=yes
# Block Redis from external access
netsh advfirewall firewall add rule name="Block-Redis-External" dir=in action=block protocol=TCP localport=6379 remoteip="localsubnet" profile=public enable=yes
# Block Docker API entirely (redundant safety)
netsh advfirewall firewall add rule name="Block-DockerAPI-All" dir=in action=block protocol=TCP localport=2375 profile=public enable=yes
# Block Redis entirely (redundant safety)  
netsh advfirewall firewall add rule name="Block-Redis-All" dir=in action=block protocol=TCP localport=6379 profile=public enable=yes

Write-Host "=== SQUIDSTATION Hardening Complete ===" -ForegroundColor Green
Write-Host "✅ All fleet services remain accessible internally" -ForegroundColor Green
Write-Host "❌ External access to Docker API (2375) and Redis (6379) blocked" -ForegroundColor Red
