@echo off
REM EMERGENCY ROLLBACK — Restores PRE-HARDENING firewall state
REM Generated by Sir Green's OODA loop
REM ⚠️ Run this ONLY if fleet connectivity breaks after hardening

echo ⚠️ EMERGENCY ROLLBACK INITIATED
echo Restoring SQUIDSTATION firewall rules...
echo.

REM Delete all Fleet Security rules
netsh advfirewall firewall delete rule name="Block-DockerAPI-Public"
netsh advfirewall firewall delete rule name="Block-DockerAPI-Domain"
netsh advfirewall firewall delete rule name="Block-Redis-Public"
netsh advfirewall firewall delete rule name="Block-Redis-Domain"
netsh advfirewall firewall delete rule name="Docker-TLS-FleetOnly"
netsh advfirewall firewall delete rule name="Dashboard-FleetOnly"
netsh advfirewall firewall delete rule name="Grafana-FleetOnly"
netsh advfirewall firewall delete rule name="Prometheus-FleetOnly"
netsh advfirewall firewall delete rule name="Alertmanager-FleetOnly"

echo ✅ All Fleet Security rules removed
echo.

REM Export current (cleaned) firewall state for audit
netsh advfirewall export "C:\Users\kidsm\Documents\Fleet_Security\firewall_rollback_state.wfw"
echo ✅ Rollback state saved to: C:\Users\kidsm\Documents\Fleet_Security\firewall_rollback_state.wfw
echo.

REM Verify Docker API (2375) accessible again
netsh advfirewall firewall show rule name="Block-DockerAPI-Public" 2>nul
if errorlevel 1 (
    echo ✅ Port 2375 no longer blocked — rollback successful
) else (
    echo ⚠️ Port 2375 still blocked — manual intervention required
)

REM Show current port status
echo.
echo === CURRENT PORT STATUS ===
netstat -an | findstr -i "2375 2376 6379 8080 3000 9090 9093"

echo.
echo 🛑 ROLLBACK COMPLETE — Fleet connectivity restored
echo 📝 Next steps: Review logs, re-enable selectively if needed
