@echo off
REM Fleet Security Hardening - SQUIDSTATION
REM Generated by Sir Green's OODA loop

REM Block Docker API (2375) on public profiles only
netsh advfirewall firewall add rule name="Block-DockerAPI-Public" dir=in action=block protocol=TCP localport=2375 remoteip=localsubnet profile=public enable=yes
netsh advfirewall firewall add rule name="Block-DockerAPI-Domain" dir=in action=block protocol=TCP localport=2375 remoteip=localsubnet profile=domain enable=yes

REM Block Redis (6379) on public profiles only
netsh advfirewall firewall add rule name="Block-Redis-Public" dir=in action=block protocol=TCP localport=6379 remoteip=localsubnet profile=public enable=yes
netsh advfirewall firewall add rule name="Block-Redis-Domain" dir=in action=block protocol=TCP localport=6379 remoteip=localsubnet profile=domain enable=yes

REM Allow Docker TLS (2376) for fleet only
netsh advfirewall firewall add rule name="Docker-TLS-FleetOnly" dir=in action=allow protocol=TCP localport=2376 remoteip="192.168.0.39,192.168.0.3,100.83.247.14,192.168.0.0/24" profile=any enable=yes

REM Allow Dashboard (8080) for fleet only
netsh advfirewall firewall add rule name="Dashboard-FleetOnly" dir=in action=allow protocol=TCP localport=8080 remoteip="192.168.0.39,192.168.0.3,100.83.247.14,192.168.0.0/24" profile=any enable=yes

REM Allow Grafana (3000) for fleet only
netsh advfirewall firewall add rule name="Grafana-FleetOnly" dir=in action=allow protocol=TCP localport=3000 remoteip="192.168.0.39,192.168.0.3,100.83.247.14,192.168.0.0/24" profile=any enable=yes

REM Allow Prometheus (9090) for fleet only
netsh advfirewall firewall add rule name="Prometheus-FleetOnly" dir=in action=allow protocol=TCP localport=9090 remoteip="192.168.0.39,192.168.0.3,100.83.247.14,192.168.0.0/24" profile=any enable=yes

REM Allow Alertmanager (9093) for fleet only
netsh advfirewall firewall add rule name="Alertmanager-FleetOnly" dir=in action=allow protocol=TCP localport=9093 remoteip="192.168.0.39,192.168.0.3,100.83.247.14,192.168.0.0/24" profile=any enable=yes

REM Verify rules applied
echo === VERIFICATION ===
netsh advfirewall firewall show rule name="Block-DockerAPI-Public"
netsh advfirewall firewall show rule name="Block-Redis-Public"
netsh advfirewall firewall show rule name="Docker-TLS-FleetOnly"
echo === HARDENING COMPLETE ===
