import win32cred, urllib.parse, http.client, json, ssl, time

c = win32cred.CredRead('TRELLO_KEY@VOID_Pirate_Secrets', 1)
key = c['CredentialBlob'].decode('utf-16le', errors='ignore').replace('\x00', '')
c = win32cred.CredRead('TRELLO_TOKEN@VOID_Pirate_Secrets', 1)
token = c['CredentialBlob'].decode('utf-16le', errors='ignore').replace('\x00', '')
ctx = ssl.create_default_context()
list_id = '6a83a587783f6d23b411a8a7'  # Backlog

def post_card(card):
    qs = 'key=' + urllib.parse.quote(key) + '&token=' + urllib.parse.quote(token) + '&idList=' + urllib.parse.quote(list_id)
    conn = http.client.HTTPSConnection('api.trello.com', context=ctx)
    conn.request('POST', '/1/cards?' + qs, json.dumps(card).encode(), {'Content-Type':'application/json'})
    r = conn.getresponse()
    data = r.read().decode()
    conn.close()
    time.sleep(0.4)
    return r.status, json.loads(data)['id']

cards = [
  {'name': '[P0] Tonight: podcast + YouTube + TikTok production setup', 'desc': 'Goal: film podcast episode and 1st YouTube video for Torus Coffee Company tonight. Deliverables: raw footage, edited podcast MP3/WAV, YouTube-ready MP4, TikTok-ready MP4 (vertical 9:16), website embed, YouTube upload, TikTok upload.\n\nHardware: use existing cameras. Software: free tools only. Platform connections: YouTube already connected; TikTok not connected yet.', 'labels': 'miss-pink,mission control,torus-coffee'},
  {'name': '[P1] Install free video/audio editing stack on PINKCADY', 'desc': 'Install order on PINKCADY:\n1) OBS Studio (free) — screen + camera capture\n2) DaVinci Resolve 18 (free) — video editing, color, audio mix\n3) Audacity (free) — podcast audio cleanup, noise reduction\n4) FFmpeg (free) — format conversion, H.264, 9:16 vertical\n5) Shotcut (free, optional) — quick-cut editor if Resolve is too heavy\n\nVerification: all apps launch, camera/mic detected, export 1080p MP4.', 'labels': 'miss-pink,mission control,torus-coffee'},
  {'name': '[P1] Install free podcast + media production skills on PINKCADY', 'desc': 'Install/prepare:\n1) OBS Studio scenes: camera + screen + mic audio mix\n2) Audacity chains: noise suppression, compressor, limiter, normalize\n3) FFmpeg commands for podcast MP3 and vertical TikTok MP4\n4) YouTube thumbnail template (free tool: Canva free tier)\n5) TikTok description + hashtag bank for Torus Coffee\n6) Brand assets: Torus Coffee logo, intro bumper, lower thirds\n\nOutput: `mission-control/src/scripts/sir-green/fleet-bootstrap/pinkcady/media-production/` with all assets and scripts.', 'labels': 'miss-pink,mission control,torus-coffee'},
  {'name': '[P0] Connect Torus Coffee TikTok account', 'desc': 'Steps:\n1) Open https://www.tiktok.com on PINKCADY browser\n2) Login to Torus Coffee TikTok account\n3) Go to Settings → Account → Link account / switch to business/creator if needed\n4) Verify upload capability: save draft with 1 test image/video\n5) Note username/handle and upload restrictions in card comment\n\nIf 2FA required, use phone on PINKCADY.\nDo NOT store TikTok password in code or Trello card.', 'labels': 'miss-pink,mission control,torus-coffee'},
  {'name': '[P1] Film podcast episode tonight — checklist', 'desc': 'Pre-film:\n- Camera charged, mic tested, OBS scenes saved\n- Backup storage available (external HDD or cloud)\n- Lights set, background clean\n\nFilm:\n- Record camera + audio separately if possible (camera video + Audacity audio) for sync flexibility\n- Record 30-60 min raw\n- Save raw files to `PINKCADY/media/raw/YYYY-MM-DD-podcast/`\n\nWrap:\n- Copy raw to backup drive immediately\n- Post card comment with file sizes and durations', 'labels': 'miss-pink,mission control,torus-coffee'},
  {'name': '[P1] Film 1st YouTube video for Torus Coffee tonight — checklist', 'desc': 'Video options:\n- Option A: Podcast teaser clip (1-3 min best moments)\n- Option B: Behind-the-scenes at Torus Coffee\n- Option C: Barista skill showcase / latte art\n\nSettings:\n- 1080p 30fps minimum, 60fps if slow motion\n- Landscape 16:9 for YouTube\n- Audio: clear, no background noise\n\nSave raw to `PINKCADY/media/raw/YYYY-MM-DD-youtube/` and backup immediately.', 'labels': 'miss-pink,mission control,torus-coffee'},
  {'name': '[P2] Edit podcast audio — tonight', 'desc': 'Audacity workflow:\n1) Import raw audio tracks\n2) Noise reduction profile (select silence → noise reduction → apply)\n3) Compressor: -18dB threshold, 3:1 ratio\n4) Normalize to -1dB peak\n5) Export WAV 48kHz + MP3 192kbps\n6) Save to `PINKCADY/media/edited/podcast/YYYY-MM-DD-podcast.mp3`\n\nPost comment with file sizes and peak levels.', 'labels': 'miss-pink,mission control,torus-coffee'},
  {'name': '[P2] Edit YouTube video — tonight', 'desc': 'DaVinci Resolve workflow:\n1) Create 1080p 30fps project\n2) Sync audio to video (pluralize if recorded separately)\n3) Color correction: warm tones for coffee shop vibe\n4) Audio mix: normalize, light compression\n5) Add intro bumper + lower thirds\n6) Export H.264 MP4, YouTube upload settings (1080p, ~20 Mbps)\n7) Save to `PINKCADY/media/edited/youtube/YYYY-MM-DD-youtube.mp4`\n\nPost comment with export settings and file size.', 'labels': 'miss-pink,mission control,torus-coffee'},
  {'name': '[P2] Edit TikTok video — tonight', 'desc': 'DaVinci Resolve / FFmpeg workflow:\n1) Select best 60-180s clip from YouTube footage\n2) Crop to 9:16 vertical (1080x1920)\n3) Add captions/subtitles (Resolve or CapCut free)\n4) Color boost for mobile viewing\n5) Export H.264 MP4 vertical, ~8 Mbps\n6) Save to `PINKCADY/media/edited/tiktok/YYYY-MM-DD-tiktok.mp4`\n\nPost comment with duration and file size.', 'labels': 'miss-pink,mission control,torus-coffee'},
  {'name': '[P0] Upload to YouTube and post to website tonight', 'desc': 'YouTube upload:\n1) Go to https://studio.youtube.com on PINKCADY\n2) Upload `YYYY-MM-DD-youtube.mp4`\n3) Title: [Torus Coffee] — [video title]\n4) Description: include links to website, Instagram, TikTok\n5) Tags: torus coffee, coffee shop, [city], latte art, etc.\n6) Thumbnail: upload custom PNG from Canva\n7) Set visibility: Unlisted first, then Public after review\n8) Copy YouTube URL\n\nWebsite:\n- Embed video on Torus Coffee homepage or /video page\n- Post comment with YouTube URL', 'labels': 'miss-pink,mission control,torus-coffee'},
  {'name': '[P0] Upload to TikTok tonight', 'desc': 'TikTok upload:\n1) Open TikTok app/web on PINKCADY\n2) Upload `YYYY-MM-DD-tiktok.mp4`\n3) Caption: Hook + Torus Coffee vibe + CTA (link in bio for website)\n4) Hashtags: #TorusCoffee #CoffeeShop #LatteArt #SmallBusiness #SupportLocal\n5) Cover frame: choose engaging frame from video\n6) Post Public\n7) Post comment with TikTok URL\n\nIf TikTok upload fails, note error in card comment.', 'labels': 'miss-pink,mission control,torus-coffee'},
  {'name': '[P1] Podcast distribution — tonight', 'desc': 'Distribution:\n1) Upload podcast MP3 to YouTube as private video (audio waveform + static image)\n2) Or upload to Anchor/Spotify for Podcasters (free)\n3) If Anchor: create account, upload MP3, add title/description, publish\n4) Post Spotify/YouTube podcast URL back here\n\nBackup: save MP3 to Google Drive for future distribution.', 'labels': 'miss-pink,mission control,torus-coffee'},
  {'name': '[P1] Post-production archive and backup checklist', 'desc': 'After all edits complete:\n1) Organize `PINKCADY/media/` into `raw/`, `edited/`, `exports/`, `archives/`\n2) Copy full `media/` to external backup drive\n3) Upload `exports/` to Google Drive (free tier)\n4) Create Trello card comment with all URLs: YouTube, TikTok, podcast, website\n5) Tag Miss Pink in Trello for review before going public\n\nArchive structure:\n```\nmedia/\n├── raw/\n│   ├── YYYY-MM-DD-podcast/\n│   └── YYYY-MM-DD-youtube/\n├── edited/\n│   ├── podcast/\n│   ├── youtube/\n│   └── tiktok/\n├── exports/\n│   ├── YYYY-MM-DD-podcast.mp3\n│   ├── YYYY-MM-DD-youtube.mp4\n│   └── YYYY-MM-DD-tiktok.mp4\n└── archives/\n```', 'labels': 'miss-pink,mission control,torus-coffee'},
  {'name': '[P2] Create reusable production SOP for Torus Coffee media', 'desc': 'Document the workflow that worked tonight so future episodes/videos are faster:\n- Equipment setup checklist\n- OBS scene config\n- Audacity audio chain settings\n- Resolve project template settings\n- Export presets (YouTube, TikTok, podcast)\n- Upload checklists for each platform\n- File naming convention\n\nSave SOP to `mission-control/src/scripts/sir-green/fleet-bootstrap/pinkcady/media-production/SOP.md`', 'labels': 'miss-pink,mission control,torus-coffee'},
  {'name': '[P2] Free AI media skills to install on PINKCADY this week', 'desc': 'Enhancement skills for future episodes (not blocking tonight):\n1) Whisper (OpenAI, free local) — auto-transcribe podcast to captions\n2) Whisper.cpp — lighter alternative for transcription\n3) Stable Diffusion (free local) — generate thumbnails, social graphics\n4) FFmpeg batch scripts — auto-generate TikTok clips from long video\n5) Canva free account — quick thumbnails, intro/outro graphics\n6) CapCut free — fast mobile/desktop edits for TikTok\n\nInstall instructions: use Python venv or portable builds, keep everything free.', 'labels': 'miss-pink,mission control,torus-coffee'},
  {'name': '[P1] Verify all platform connections and go-live readiness', 'desc': 'Pre-publish checklist:\n- [ ] YouTube channel connected and verified\n- [ ] TikTok account connected and verified\n- [ ] Website CMS ready to embed video\n- [ ] All exported files playable on PINKCADY\n- [ ] Backup copies on external drive\n- [ ] Thumbnail ready for YouTube\n- [ ] Social captions + hashtags drafted\n- [ ] Miss Pink reviewed all content\n\nDo NOT publish until all checkboxes are green. Post screenshot proof back here.', 'labels': 'miss-pink,mission control,torus-coffee'},
]

for card in cards:
    s, cid = post_card(card)
    print(s, cid, card['name'][:70])
    time.sleep(0.3)
