#!/usr/bin/env python
"""
Hermes Fleet Recovery Script — By Sir Green
Recovers Hermes app on any fleet PC while preserving local profile data.

USAGE:
    python hermes_fleet_recovery.py backup    # Backup current profile
    python hermes_fleet_recovery.py restore   # Restore from latest backup
    python hermes_fleet_recovery.py verify    # Check profile integrity
    python hermes_fleet_recovery.py uninstall # Clean uninstall (keeps profile)
    python hermes_fleet_recovery.py diagnose  # Diagnose boot issues

ENVIRONMENT VARIABLES:
    RECOVERY_BACKUP_DIR  # Where to store backups (default: Z:\hermes_backups)
    HERMEOUS_PROFILE_DIR  # Override default profile location
"""
# ---
# This script was generated by Sir Green for VOID Pirate fleet recovery
# See: Obsidian_Vault/02_Business_Operations/_Hub/RECOVERY_PLAYBOOK_HERMES_FLEET.md
# ---

import os
import sys
import shutil
import json
import subprocess
import glob
from pathlib import Path
from datetime import datetime

# Configuration
LOCALAPPDATA = os.environ.get('LOCALAPPDATA', os.path.expandvars('%LOCALAPPDATA%'))
HERMES_DIR = os.path.join(LOCALAPPDATA, 'hermes')
BACKUP_DIR = os.environ.get('RECOVERY_BACKUP_DIR', r'Z:\hermes_backups')
PC_NAME = os.environ.get('COMPUTERNAME', os.environ.get('HOSTNAME', 'UNKNOWN'))
TIMESTAMP = datetime.now().strftime('%Y%m%d_%H%M%S')
BACKUP_NAME = f"hermes_{PC_NAME}_{TIMESTAMP}"
SKIP_DIRS = ['node', 'cache', 'image_cache', 'bootstrap-cache', '.curator_backups']

# Critical files that MUST exist for recovery
CRITICAL_FILES = [
    'SOUL.md',
    'config.yaml',
    'profile.yaml',
    'auth.json',
    os.path.join('memories', 'MEMORY.md'),
    os.path.join('memories', 'USER.md'),
]

def print_banner():
    print(f"""
╔══════════════════════════════════════════════════════╗
║  🚢 VOID PIRATE FLEET — Hermes Recovery Tool          ║
║  PC: {PC_NAME:12} | Mode: {sys.argv[1] if len(sys.argv)>1 else 'NONE':16} ║
║  Hermes Dir: {HERMES_DIR[:40]:40} ║
╚══════════════════════════════════════════════════════╝
    """)

def verify_hermes_dir():
    if not os.path.exists(HERMES_DIR):
        print(f"❌ Hermes directory not found: {HERMES_DIR}")
        return False
    print(f"✅ Hermes directory found: {HERMES_DIR}")
    return True

def backup():
    """Phase 1: Backup current profile"""
    print_banner()
    if not verify_hermes_dir():
        return False

    backup_path = os.path.join(BACKUP_DIR, BACKUP_NAME)
    print(f"📦 Creating backup: {backup_path}")

    # Create backup directory
    os.makedirs(backup_path, exist_ok=True)

    # Copy files (excluding skip dirs)
    for item in os.listdir(HERMES_DIR):
        src = os.path.join(HERMES_DIR, item)
        dst = os.path.join(backup_path, item)
        if item in SKIP_DIRS or item.startswith('.'):
            print(f"  ⏭️  Skipping: {item}")
            continue
        try:
            if os.path.isdir(src):
                shutil.copytree(src, dst, dirs_exist_ok=True)
            else:
                shutil.copy2(src, dst)
            print(f"  ✅ Copied: {item}")
        except Exception as e:
            print(f"  ❌ Error copying {item}: {e}")

    print(f"\n✅ Backup complete: {backup_path}")

    # Save backup manifest
    manifest_path = os.path.join(backup_path, 'recovery_manifest.json')
    manifest = {
        'pc_name': PC_NAME,
        'timestamp': TIMESTAMP,
        'hermes_dir': HERMES_DIR,
        'critical_files': {},
    }
    for f in CRITICAL_FILES:
        fp = os.path.join(HERMES_DIR, f)
        manifest['critical_files'][f] = {
            'exists': os.path.exists(fp),
            'size': os.path.getsize(fp) if os.path.exists(fp) else 0,
        }

    with open(manifest_path, 'w') as f:
        json.dump(manifest, f, indent=2)
    print(f"   Manifest saved: {manifest_path}")

    return True

def verify():
    """Phase 5: Verify profile integrity"""
    print_banner()
    print("🔍 Verifying profile integrity...")

    if not verify_hermes_dir():
        return False

    all_ok = True
    for f in CRITICAL_FILES:
        fp = os.path.join(HERMES_DIR, f)
        if os.path.exists(fp):
            size = os.path.getsize(fp)
            status = '✅' if size > 0 else '⚠️'
            print(f"  {status} {f} ({size} bytes)")
            if size == 0:
                print(f"     ⚠️ WARNING: File is empty!")
        else:
            print(f"  ❌ {f} — MISSING!")
            all_ok = False

    print(f"\n{'✅ All critical files present' if all_ok else '❌ Some critical files missing!'}")
    return all_ok

def diagnose():
    """Diagnose boot/log issues"""
    print_banner()
    print("🔧 Diagnosing Hermes boot issues...")

    # Check processes
    print("\n1. Checking running processes...")
    try:
        result = subprocess.run(['tasklist', '/FO', 'CSV'], capture_output=True, text=True, timeout=5)
        for line in result.stdout.split('\n'):
            if 'hermes' in line.lower() or 'python' in line.lower() and 'hermes' in line.lower():
                print(f"   {line.strip()}")
    except Exception as e:
        print(f"   Error: {e}")

    # Check state.db
    state_db = os.path.join(HERMES_DIR, 'state.db')
    if os.path.exists(state_db):
        size_gb = os.path.getsize(state_db) / (1024**3)
        print(f"\n2. State database: {size_gb:.2f} GB")
        if size_gb > 2.0:
            print(f"   ⚠️ WARNING: state.db is very large ({size_gb:.2f} GB) — may cause boot slowdown")
    else:
        print(f"\n2. State database: NOT FOUND")

    # Check for lock files
    locks = glob.glob(os.path.join(HERMES_DIR, '*.lock'))
    if locks:
        print(f"\n3. Lock files found: {len(locks)}")
        for l in locks:
            print(f"   {os.path.basename(l)}")
    else:
        print(f"\n3. No lock files — clean")

    # Check logs
    logs_dir = os.path.join(HERMES_DIR, 'logs')
    if os.path.exists(logs_dir):
        logs = sorted(glob.glob(os.path.join(logs_dir, '*.log*')), key=os.path.getmtime)
        if logs:
            latest = logs[-1]
            print(f"\n4. Latest log: {os.path.basename(latest)}")
            with open(latest, 'r', errors='ignore') as f:
                lines = f.readlines()
                for line in lines[-10:]:
                    print(f"   {line.rstrip()[:100]}")
    else:
        print(f"\n4. Logs directory: NOT FOUND")

    print("\n✅ Diagnosis complete")

def uninstall():
    """Clean uninstall while preserving profile"""
    print_banner()
    print("🗑️ Preparing clean uninstall (preserving profile data)...")

    profile_backup = HERMES_DIR + '.recovery_backup'

    if os.path.exists(profile_backup):
        print(f"⚠️ Backup already exists: {profile_backup}")
    else:
        print(f"📦 Backing up profile to: {profile_backup}")
        shutil.move(HERMES_DIR, profile_backup)

    print("\n✅ Profile backed up. Can now perform clean install.")
    print(f"   To restore: rename '{profile_backup}' back to '{HERMES_DIR}'")

def restore():
    """Restore from latest backup"""
    print_banner()
    print("🔄 Restoring from backup...")

    if not os.path.exists(BACKUP_DIR):
        print(f"❌ Backup directory not found: {BACKUP_DIR}")
        return False

    backups = sorted(glob.glob(os.path.join(BACKUP_DIR, f"hermes_{PC_NAME}_*")), key=os.path.getmtime)
    if not backups:
        print(f"❌ No backups found for {PC_NAME}")
        return False

    latest = backups[-1]
    print(f"Latest backup: {os.path.basename(latest)}")

    print("\n⚠️  This will overwrite current Hermes profile in:")
    print(f"   {HERMES_DIR}")
    response = input("Type 'YES' to confirm overwrite: ")

    if response != 'YES':
        print("❌ Restore cancelled")
        return False

    # Backup current, if exists
    if os.path.exists(HERMES_DIR):
        temp_backup = HERMES_DIR + '.pre_restore'
        print(f"Backing up current to: {temp_backup}")
        shutil.move(HERMES_DIR, temp_backup)

    # Restore
    print(f"Restoring from: {latest}")
    shutil.copytree(latest, HERMES_DIR, dirs_exist_ok=True)
    print(f"✅ Restored to: {HERMES_DIR}")

    # Verify
    print("\nVerifying restored files...")
    verify()

    return True

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print_banner()
        print("Usage: python hermes_fleet_recovery.py <command>\n")
        print("Commands:")
        print("  backup    — Backup current Hermes profile")
        print("  restore   — Restore from latest backup")
        print("  verify    — Verify profile integrity")
        print("  uninstall — Move profile to backup for clean reinstall")
        print("  diagnose  — Diagnose boot/log issues")
        sys.exit(1)

    cmd = sys.argv[1].lower()
    if cmd == 'backup':
        backup()
    elif cmd == 'restore':
        restore()
    elif cmd == 'verify':
        verify()
    elif cmd == 'uninstall':
        uninstall()
    elif cmd == 'diagnose':
        diagnose()
    else:
        print(f"Unknown command: {cmd}")
        sys.exit(1)
