@echo off
REM Fleet Security Hardening - SQUIDSTATION
REM Captain's Dashboard Integration - Fleet Security
REM Generated by Sir Green's OODA loop

netsh advfirewall firewall add rule name="Block-DockerAPI-Public" dir=in action=block protocol=TCP localport=2375 remoteip=localsubnet profile=public enable=yes
netsh advfirewall firewall add rule name="Block-DockerAPI-Domain" dir=in action=block protocol=TCP localport=2375 remoteip=localsubnet profile=domain enable=yes
netsh advfirewall firewall add rule name="Block-Redis-Public" dir=in action=block protocol=TCP localport=6379 remoteip=localsubnet profile=public enable=yes
netsh advfirewall firewall add rule name="Block-Redis-Domain" dir=in action=block protocol=TCP localport=6379 remoteip=localsubnet profile=domain enable=yes
netsh advfirewall firewall add rule name="Docker-TLS-FleetOnly" dir=in action=allow protocol=TCP localport=2376 remoteip="192.168.0.39,192.168.0.3,100.83.247.14,192.168.0.0/24" profile=any enable=yes
netsh advfirewall firewall add rule name="Dashboard-FleetOnly" dir=in action=allow protocol=TCP localport=8080 remoteip="192.168.0.39,192.168.0.3,100.83.247.14,192.168.0.0/24" profile=any enable=yes
netsh advfirewall firewall add rule name="Grafana-FleetOnly" dir=in action=allow protocol=TCP localport=3000 remoteip="192.168.0.39,192.168.0.3,100.83.247.14,192.168.0.0/24" profile=any enable=yes
netsh advfirewall firewall add rule name="Prometheus-FleetOnly" dir=in action=allow protocol=TCP localport=9090 remoteip="192.168.0.39,192.168.0.3,100.83.247.14,192.168.0.0/24" profile=any enable=yes
netsh advfirewall firewall add rule name="Alertmanager-FleetOnly" dir=in action=allow protocol=TCP localport=9093 remoteip="192.168.0.39,192.168.0.3,100.83.247.14,192.168.0.0/24" profile=any enable=yes

echo === Verification ===
netsh advfirewall firewall show rule name="Block-DockerAPI-Public"
netsh advfirewall firewall show rule name="Docker-TLS-FleetOnly"
echo === Fleet Hardening Complete ===
