-- Crew Agent Cleanup Script
-- Generated: 2026-09-10T11:39:10.201410
-- Total agents: 37
-- Stale (>7 days): 25
-- Duplicates: 0
-- Total to remove: 25

-- WARNING: Review before running! This will permanently delete agents.
-- Review the JSON report first: tools/audit_report.json

BEGIN TRANSACTION;

-- Step 1: Remove related records from child tables first
DELETE FROM tasks WHERE assigned_to IN ('firecrawl', 'firecrawl-agent', 'firecrawl-competitive-intel', 'firecrawl-dashboard-reporting', 'firecrawl-deep-research', 'firecrawl-demo-walkthrough', 'firecrawl-developer-index', 'firecrawl-knowledge-base', 'firecrawl-knowledge-ingest', 'firecrawl-lead-gen', 'firecrawl-lead-research', 'firecrawl-map', 'firecrawl-market-research', 'firecrawl-monitor', 'firecrawl-parse', 'firecrawl-qa', 'firecrawl-research-index', 'firecrawl-research-papers', 'firecrawl-scrape', 'firecrawl-search', 'firecrawl-seo-audit', 'firecrawl-shop', 'firecrawl-website-design-clone', 'firecrawl-workflows', 'test-agent');
DELETE FROM task_subscriptions WHERE agent_name IN ('firecrawl', 'firecrawl-agent', 'firecrawl-competitive-intel', 'firecrawl-dashboard-reporting', 'firecrawl-deep-research', 'firecrawl-demo-walkthrough', 'firecrawl-developer-index', 'firecrawl-knowledge-base', 'firecrawl-knowledge-ingest', 'firecrawl-lead-gen', 'firecrawl-lead-research', 'firecrawl-map', 'firecrawl-market-research', 'firecrawl-monitor', 'firecrawl-parse', 'firecrawl-qa', 'firecrawl-research-index', 'firecrawl-research-papers', 'firecrawl-scrape', 'firecrawl-search', 'firecrawl-seo-audit', 'firecrawl-shop', 'firecrawl-website-design-clone', 'firecrawl-workflows', 'test-agent');
DELETE FROM messages WHERE from_agent IN ('firecrawl', 'firecrawl-agent', 'firecrawl-competitive-intel', 'firecrawl-dashboard-reporting', 'firecrawl-deep-research', 'firecrawl-demo-walkthrough', 'firecrawl-developer-index', 'firecrawl-knowledge-base', 'firecrawl-knowledge-ingest', 'firecrawl-lead-gen', 'firecrawl-lead-research', 'firecrawl-map', 'firecrawl-market-research', 'firecrawl-monitor', 'firecrawl-parse', 'firecrawl-qa', 'firecrawl-research-index', 'firecrawl-research-papers', 'firecrawl-scrape', 'firecrawl-search', 'firecrawl-seo-audit', 'firecrawl-shop', 'firecrawl-website-design-clone', 'firecrawl-workflows', 'test-agent');
DELETE FROM messages WHERE to_agent IN ('firecrawl', 'firecrawl-agent', 'firecrawl-competitive-intel', 'firecrawl-dashboard-reporting', 'firecrawl-deep-research', 'firecrawl-demo-walkthrough', 'firecrawl-developer-index', 'firecrawl-knowledge-base', 'firecrawl-knowledge-ingest', 'firecrawl-lead-gen', 'firecrawl-lead-research', 'firecrawl-map', 'firecrawl-market-research', 'firecrawl-monitor', 'firecrawl-parse', 'firecrawl-qa', 'firecrawl-research-index', 'firecrawl-research-papers', 'firecrawl-scrape', 'firecrawl-search', 'firecrawl-seo-audit', 'firecrawl-shop', 'firecrawl-website-design-clone', 'firecrawl-workflows', 'test-agent');
DELETE FROM user_sessions WHERE user_agent IN ('firecrawl', 'firecrawl-agent', 'firecrawl-competitive-intel', 'firecrawl-dashboard-reporting', 'firecrawl-deep-research', 'firecrawl-demo-walkthrough', 'firecrawl-developer-index', 'firecrawl-knowledge-base', 'firecrawl-knowledge-ingest', 'firecrawl-lead-gen', 'firecrawl-lead-research', 'firecrawl-map', 'firecrawl-market-research', 'firecrawl-monitor', 'firecrawl-parse', 'firecrawl-qa', 'firecrawl-research-index', 'firecrawl-research-papers', 'firecrawl-scrape', 'firecrawl-search', 'firecrawl-seo-audit', 'firecrawl-shop', 'firecrawl-website-design-clone', 'firecrawl-workflows', 'test-agent');
DELETE FROM workflow_templates WHERE agent_role IN ('firecrawl', 'firecrawl-agent', 'firecrawl-competitive-intel', 'firecrawl-dashboard-reporting', 'firecrawl-deep-research', 'firecrawl-demo-walkthrough', 'firecrawl-developer-index', 'firecrawl-knowledge-base', 'firecrawl-knowledge-ingest', 'firecrawl-lead-gen', 'firecrawl-lead-research', 'firecrawl-map', 'firecrawl-market-research', 'firecrawl-monitor', 'firecrawl-parse', 'firecrawl-qa', 'firecrawl-research-index', 'firecrawl-research-papers', 'firecrawl-scrape', 'firecrawl-search', 'firecrawl-seo-audit', 'firecrawl-shop', 'firecrawl-website-design-clone', 'firecrawl-workflows', 'test-agent');
DELETE FROM audit_log WHERE user_agent IN ('firecrawl', 'firecrawl-agent', 'firecrawl-competitive-intel', 'firecrawl-dashboard-reporting', 'firecrawl-deep-research', 'firecrawl-demo-walkthrough', 'firecrawl-developer-index', 'firecrawl-knowledge-base', 'firecrawl-knowledge-ingest', 'firecrawl-lead-gen', 'firecrawl-lead-research', 'firecrawl-map', 'firecrawl-market-research', 'firecrawl-monitor', 'firecrawl-parse', 'firecrawl-qa', 'firecrawl-research-index', 'firecrawl-research-papers', 'firecrawl-scrape', 'firecrawl-search', 'firecrawl-seo-audit', 'firecrawl-shop', 'firecrawl-website-design-clone', 'firecrawl-workflows', 'test-agent');
DELETE FROM direct_connections WHERE agent_id IN ('firecrawl', 'firecrawl-agent', 'firecrawl-competitive-intel', 'firecrawl-dashboard-reporting', 'firecrawl-deep-research', 'firecrawl-demo-walkthrough', 'firecrawl-developer-index', 'firecrawl-knowledge-base', 'firecrawl-knowledge-ingest', 'firecrawl-lead-gen', 'firecrawl-lead-research', 'firecrawl-map', 'firecrawl-market-research', 'firecrawl-monitor', 'firecrawl-parse', 'firecrawl-qa', 'firecrawl-research-index', 'firecrawl-research-papers', 'firecrawl-scrape', 'firecrawl-search', 'firecrawl-seo-audit', 'firecrawl-shop', 'firecrawl-website-design-clone', 'firecrawl-workflows', 'test-agent');
DELETE FROM token_usage WHERE agent_name IN ('firecrawl', 'firecrawl-agent', 'firecrawl-competitive-intel', 'firecrawl-dashboard-reporting', 'firecrawl-deep-research', 'firecrawl-demo-walkthrough', 'firecrawl-developer-index', 'firecrawl-knowledge-base', 'firecrawl-knowledge-ingest', 'firecrawl-lead-gen', 'firecrawl-lead-research', 'firecrawl-map', 'firecrawl-market-research', 'firecrawl-monitor', 'firecrawl-parse', 'firecrawl-qa', 'firecrawl-research-index', 'firecrawl-research-papers', 'firecrawl-scrape', 'firecrawl-search', 'firecrawl-seo-audit', 'firecrawl-shop', 'firecrawl-website-design-clone', 'firecrawl-workflows', 'test-agent');
DELETE FROM project_agent_assignments WHERE agent_name IN ('firecrawl', 'firecrawl-agent', 'firecrawl-competitive-intel', 'firecrawl-dashboard-reporting', 'firecrawl-deep-research', 'firecrawl-demo-walkthrough', 'firecrawl-developer-index', 'firecrawl-knowledge-base', 'firecrawl-knowledge-ingest', 'firecrawl-lead-gen', 'firecrawl-lead-research', 'firecrawl-map', 'firecrawl-market-research', 'firecrawl-monitor', 'firecrawl-parse', 'firecrawl-qa', 'firecrawl-research-index', 'firecrawl-research-papers', 'firecrawl-scrape', 'firecrawl-search', 'firecrawl-seo-audit', 'firecrawl-shop', 'firecrawl-website-design-clone', 'firecrawl-workflows', 'test-agent');
DELETE FROM security_events WHERE agent_name IN ('firecrawl', 'firecrawl-agent', 'firecrawl-competitive-intel', 'firecrawl-dashboard-reporting', 'firecrawl-deep-research', 'firecrawl-demo-walkthrough', 'firecrawl-developer-index', 'firecrawl-knowledge-base', 'firecrawl-knowledge-ingest', 'firecrawl-lead-gen', 'firecrawl-lead-research', 'firecrawl-map', 'firecrawl-market-research', 'firecrawl-monitor', 'firecrawl-parse', 'firecrawl-qa', 'firecrawl-research-index', 'firecrawl-research-papers', 'firecrawl-scrape', 'firecrawl-search', 'firecrawl-seo-audit', 'firecrawl-shop', 'firecrawl-website-design-clone', 'firecrawl-workflows', 'test-agent');
DELETE FROM agent_trust_scores WHERE agent_name IN ('firecrawl', 'firecrawl-agent', 'firecrawl-competitive-intel', 'firecrawl-dashboard-reporting', 'firecrawl-deep-research', 'firecrawl-demo-walkthrough', 'firecrawl-developer-index', 'firecrawl-knowledge-base', 'firecrawl-knowledge-ingest', 'firecrawl-lead-gen', 'firecrawl-lead-research', 'firecrawl-map', 'firecrawl-market-research', 'firecrawl-monitor', 'firecrawl-parse', 'firecrawl-qa', 'firecrawl-research-index', 'firecrawl-research-papers', 'firecrawl-scrape', 'firecrawl-search', 'firecrawl-seo-audit', 'firecrawl-shop', 'firecrawl-website-design-clone', 'firecrawl-workflows', 'test-agent');
DELETE FROM mcp_call_log WHERE agent_name IN ('firecrawl', 'firecrawl-agent', 'firecrawl-competitive-intel', 'firecrawl-dashboard-reporting', 'firecrawl-deep-research', 'firecrawl-demo-walkthrough', 'firecrawl-developer-index', 'firecrawl-knowledge-base', 'firecrawl-knowledge-ingest', 'firecrawl-lead-gen', 'firecrawl-lead-research', 'firecrawl-map', 'firecrawl-market-research', 'firecrawl-monitor', 'firecrawl-parse', 'firecrawl-qa', 'firecrawl-research-index', 'firecrawl-research-papers', 'firecrawl-scrape', 'firecrawl-search', 'firecrawl-seo-audit', 'firecrawl-shop', 'firecrawl-website-design-clone', 'firecrawl-workflows', 'test-agent');
DELETE FROM eval_runs WHERE agent_name IN ('firecrawl', 'firecrawl-agent', 'firecrawl-competitive-intel', 'firecrawl-dashboard-reporting', 'firecrawl-deep-research', 'firecrawl-demo-walkthrough', 'firecrawl-developer-index', 'firecrawl-knowledge-base', 'firecrawl-knowledge-ingest', 'firecrawl-lead-gen', 'firecrawl-lead-research', 'firecrawl-map', 'firecrawl-market-research', 'firecrawl-monitor', 'firecrawl-parse', 'firecrawl-qa', 'firecrawl-research-index', 'firecrawl-research-papers', 'firecrawl-scrape', 'firecrawl-search', 'firecrawl-seo-audit', 'firecrawl-shop', 'firecrawl-website-design-clone', 'firecrawl-workflows', 'test-agent');
DELETE FROM eval_traces WHERE agent_name IN ('firecrawl', 'firecrawl-agent', 'firecrawl-competitive-intel', 'firecrawl-dashboard-reporting', 'firecrawl-deep-research', 'firecrawl-demo-walkthrough', 'firecrawl-developer-index', 'firecrawl-knowledge-base', 'firecrawl-knowledge-ingest', 'firecrawl-lead-gen', 'firecrawl-lead-research', 'firecrawl-map', 'firecrawl-market-research', 'firecrawl-monitor', 'firecrawl-parse', 'firecrawl-qa', 'firecrawl-research-index', 'firecrawl-research-papers', 'firecrawl-scrape', 'firecrawl-search', 'firecrawl-seo-audit', 'firecrawl-shop', 'firecrawl-website-design-clone', 'firecrawl-workflows', 'test-agent');
DELETE FROM agent_api_keys WHERE agent_id IN ('firecrawl', 'firecrawl-agent', 'firecrawl-competitive-intel', 'firecrawl-dashboard-reporting', 'firecrawl-deep-research', 'firecrawl-demo-walkthrough', 'firecrawl-developer-index', 'firecrawl-knowledge-base', 'firecrawl-knowledge-ingest', 'firecrawl-lead-gen', 'firecrawl-lead-research', 'firecrawl-map', 'firecrawl-market-research', 'firecrawl-monitor', 'firecrawl-parse', 'firecrawl-qa', 'firecrawl-research-index', 'firecrawl-research-papers', 'firecrawl-scrape', 'firecrawl-search', 'firecrawl-seo-audit', 'firecrawl-shop', 'firecrawl-website-design-clone', 'firecrawl-workflows', 'test-agent');
DELETE FROM spawn_history WHERE agent_id IN ('firecrawl', 'firecrawl-agent', 'firecrawl-competitive-intel', 'firecrawl-dashboard-reporting', 'firecrawl-deep-research', 'firecrawl-demo-walkthrough', 'firecrawl-developer-index', 'firecrawl-knowledge-base', 'firecrawl-knowledge-ingest', 'firecrawl-lead-gen', 'firecrawl-lead-research', 'firecrawl-map', 'firecrawl-market-research', 'firecrawl-monitor', 'firecrawl-parse', 'firecrawl-qa', 'firecrawl-research-index', 'firecrawl-research-papers', 'firecrawl-scrape', 'firecrawl-search', 'firecrawl-seo-audit', 'firecrawl-shop', 'firecrawl-website-design-clone', 'firecrawl-workflows', 'test-agent');
DELETE FROM spawn_history WHERE agent_name IN ('firecrawl', 'firecrawl-agent', 'firecrawl-competitive-intel', 'firecrawl-dashboard-reporting', 'firecrawl-deep-research', 'firecrawl-demo-walkthrough', 'firecrawl-developer-index', 'firecrawl-knowledge-base', 'firecrawl-knowledge-ingest', 'firecrawl-lead-gen', 'firecrawl-lead-research', 'firecrawl-map', 'firecrawl-market-research', 'firecrawl-monitor', 'firecrawl-parse', 'firecrawl-qa', 'firecrawl-research-index', 'firecrawl-research-papers', 'firecrawl-scrape', 'firecrawl-search', 'firecrawl-seo-audit', 'firecrawl-shop', 'firecrawl-website-design-clone', 'firecrawl-workflows', 'test-agent');
DELETE FROM runs WHERE agent_id IN ('firecrawl', 'firecrawl-agent', 'firecrawl-competitive-intel', 'firecrawl-dashboard-reporting', 'firecrawl-deep-research', 'firecrawl-demo-walkthrough', 'firecrawl-developer-index', 'firecrawl-knowledge-base', 'firecrawl-knowledge-ingest', 'firecrawl-lead-gen', 'firecrawl-lead-research', 'firecrawl-map', 'firecrawl-market-research', 'firecrawl-monitor', 'firecrawl-parse', 'firecrawl-qa', 'firecrawl-research-index', 'firecrawl-research-papers', 'firecrawl-scrape', 'firecrawl-search', 'firecrawl-seo-audit', 'firecrawl-shop', 'firecrawl-website-design-clone', 'firecrawl-workflows', 'test-agent');
DELETE FROM runs WHERE agent_name IN ('firecrawl', 'firecrawl-agent', 'firecrawl-competitive-intel', 'firecrawl-dashboard-reporting', 'firecrawl-deep-research', 'firecrawl-demo-walkthrough', 'firecrawl-developer-index', 'firecrawl-knowledge-base', 'firecrawl-knowledge-ingest', 'firecrawl-lead-gen', 'firecrawl-lead-research', 'firecrawl-map', 'firecrawl-market-research', 'firecrawl-monitor', 'firecrawl-parse', 'firecrawl-qa', 'firecrawl-research-index', 'firecrawl-research-papers', 'firecrawl-scrape', 'firecrawl-search', 'firecrawl-seo-audit', 'firecrawl-shop', 'firecrawl-website-design-clone', 'firecrawl-workflows', 'test-agent');
DELETE FROM agent_keys WHERE agent_id IN ('firecrawl', 'firecrawl-agent', 'firecrawl-competitive-intel', 'firecrawl-dashboard-reporting', 'firecrawl-deep-research', 'firecrawl-demo-walkthrough', 'firecrawl-developer-index', 'firecrawl-knowledge-base', 'firecrawl-knowledge-ingest', 'firecrawl-lead-gen', 'firecrawl-lead-research', 'firecrawl-map', 'firecrawl-market-research', 'firecrawl-monitor', 'firecrawl-parse', 'firecrawl-qa', 'firecrawl-research-index', 'firecrawl-research-papers', 'firecrawl-scrape', 'firecrawl-search', 'firecrawl-seo-audit', 'firecrawl-shop', 'firecrawl-website-design-clone', 'firecrawl-workflows', 'test-agent');
DELETE FROM ship_agents WHERE agent_id IN ('firecrawl', 'firecrawl-agent', 'firecrawl-competitive-intel', 'firecrawl-dashboard-reporting', 'firecrawl-deep-research', 'firecrawl-demo-walkthrough', 'firecrawl-developer-index', 'firecrawl-knowledge-base', 'firecrawl-knowledge-ingest', 'firecrawl-lead-gen', 'firecrawl-lead-research', 'firecrawl-map', 'firecrawl-market-research', 'firecrawl-monitor', 'firecrawl-parse', 'firecrawl-qa', 'firecrawl-research-index', 'firecrawl-research-papers', 'firecrawl-scrape', 'firecrawl-search', 'firecrawl-seo-audit', 'firecrawl-shop', 'firecrawl-website-design-clone', 'firecrawl-workflows', 'test-agent');
DELETE FROM gateways WHERE agents_count IN ('firecrawl', 'firecrawl-agent', 'firecrawl-competitive-intel', 'firecrawl-dashboard-reporting', 'firecrawl-deep-research', 'firecrawl-demo-walkthrough', 'firecrawl-developer-index', 'firecrawl-knowledge-base', 'firecrawl-knowledge-ingest', 'firecrawl-lead-gen', 'firecrawl-lead-research', 'firecrawl-map', 'firecrawl-market-research', 'firecrawl-monitor', 'firecrawl-parse', 'firecrawl-qa', 'firecrawl-research-index', 'firecrawl-research-papers', 'firecrawl-scrape', 'firecrawl-search', 'firecrawl-seo-audit', 'firecrawl-shop', 'firecrawl-website-design-clone', 'firecrawl-workflows', 'test-agent');

-- Step 2: Remove agent entries (IDs: 1, 2, 4, 6, 7, 8, 9, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29)
DELETE FROM agents WHERE id IN (1, 2, 4, 6, 7, 8, 9, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29);

COMMIT;

-- Verification:
SELECT COUNT(*) AS remaining_after_cleanup FROM agents;
